version: '3'
services:
  app:
    build: ./demo
    env_file:
      - app.env
    depends_on:
      - redis
      - postgres
    deploy:
      replicas: 3
    networks:
      - docker-network

  redis:
    image: redis:latest
    env_file:
      - redis.env
    networks:
      - docker-network

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    env_file:
      - postgres.env
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge